### ISSUE TITLE
How to use Donut model?

### ISSUE THREAD

**Issue by AliAzG** [KDD-OpenSource/DeepADoTS#188]
how can I use Donut model with a time series data?
I have searched a lot to find an example but did not find any.
Can anybody please show me an example of using Donut model and how it detects the anomalies?
Thanks in advance.

**Comment by WGierke** [comment]
I think the [original implementation](https://github.com/haowen-xu/donut) of the authors is a good starting point to understand the usage of the algorithm since they also provide detailed examples.
