### ISSUE TITLE
Incompatible with recent tfsnippets releases

### ISSUE THREAD

**Issue by rob-med** [KDD-OpenSource/DeepADoTS#191]
The repository seems to be incompatible with the recent releases of [tfsnippets](https://github.com/haowen-xu/tfsnippet). Infact, it looks like the **modules** package has been removed since the v0.2.0-alpha.1 release (see [changelog](https://github.com/haowen-xu/tfsnippet/blob/7b43abdbdd29f1914dbc11b961b5d45b9de76653/CHANGELOG.md)).

The last compatible commit seem to be [this one.](https://github.com/haowen-xu/tfsnippet/commit/ecc0b4d1e610cf8cfa8c236857a7dabee27d5543). It can be installed by setting in the requirements.txt:

` pip install git+https://github.com/korepwx/tfsnippet.git@ecc0b4d1e610cf8cfa8c236857a7dabee27d5543
`

**Comment by WGierke** [comment]
@rob-med I just changed it on the master. Thanks Roberto!
