### ISSUE TITLE
ModuleNotFoundError: No module named 'agots.generators'

### ISSUE THREAD

**Issue by Donek1** [KDD-OpenSource/DeepADoTS#212]
i have used "pip install -r requirements.txt" but it still have some problems. why?

**Comment by Chaoste** [comment]
I can't tell you how we set this up back then but maybe you get it working by installing agots separately - see this line in the requirements: https://github.com/KDD-OpenSource/DeepADoTS/blob/master/requirements.txt#L2
We were using pip eggs, so maybe you need to find out on your own how to create and use those eggs. Probably, you create them by checking out [agots](https://github.com/KDD-OpenSource/agots) and building it via the `setup.py`.

**Comment by Donek1** [comment]
> I can't tell you how we set this up back then but maybe you get it working by installing agots separately - see this line in the requirements: https://github.com/KDD-OpenSource/DeepADoTS/blob/master/requirements.txt#L2 We were using pip eggs, so maybe you need to find out on your own how to create and use those eggs. Probably, you create them by checking out [agots](https://github.com/KDD-OpenSource/agots) and building it via the `setup.py`.

Thanks, i haved solved this question.
